spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/trello_dev
    username: root
    password: 1234
  kafka:
    bootstrap-servers:
      - http://localhost:9092

logging:
  level:
    sql: INFO